 SELECT -- A.ID AS PARENT, B.ID AS CHILD , A.PARENT_ID, 
-- A.ID AS A_ID
-- , A.PARENT_ID AS A_P
 -- , B.ID AS B_I
 -- , B.PARENT_ID AS B_P
  C.ID 
 -- , C.PARENT_ID AS C_P
 FROM ECOLI_DATA A
 JOIN ECOLI_DATA B ON B.PARENT_ID = A.ID
 JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID
 WHERE A.PARENT_ID IS  NULL
 ORDER BY C.ID ASC;



-- SELECT D3.ID
-- FROM ECOLI_DATA D1 INNER JOIN ECOLI_DATA D2 ON D1.ID=D2.PARENT_ID
-- INNER JOIN ECOLI_DATA D3 ON D2.ID=D3.PARENT_ID
-- WHERE D1.PARENT_ID IS NULL
-- ORDER BY D3.ID;